[package]
name = "rloxj"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
by_address = "1.1.0"
clap = "4.3.22"
downcast-rs = "1.2.0"
rustyline = "12.0.0"
